NullTraining/project-team2

.gitignore

Dodao sam .idea dir u .gitignore, to su phpstorp project fileovi

Addes .idea to .gitignore. This is PhpStorm project files directory

---

.gitignore
composer.json

added doctrine and fixed typo in .gitignore
after `php composer.phar install` edit your .env file with the following:
`DATABASE_URL=mysql://bob:n0p455@127.0.0.1:3306/bob_dev`

Add doctrine

---

composer.lock
config/bundles.php
config/packages/doctrine.yaml
config/packages/doctrine_migrations.yaml
config/packages/prod/doctrine.yaml
phpunit.xml.dist
symfony.lock

Will also add composer/symfony lock files so we can have the same package version

Add files generated by doctrine/maker install to VCS

---

composer.lock
config/bundles.php
config/packages/twig.yaml
config/routes/dev/twig.yaml
symfony.lock
templates/base.html.twig

After running 'composer update' composer.json and composer.lock are now in sync.
Closes #25 .

#25 - Add up-to-date composer.lock, twig-generated configuration

---

README.md

README.md is updated with project specs and description
Closes #28

#28 - Added project specs and description to README.md

---

composer.json
composer.lock
config/bundles.php
config/packages/dev/easy_log_handler.yaml
config/packages/dev/monolog.yaml
config/packages/dev/web_profiler.yaml
config/packages/prod/monolog.yaml
config/packages/test/web_profiler.yaml
config/routes/dev/web_profiler.yaml
symfony.lock

Add symfony, composer locks, composer.json and configuration

#10 - Add debug-pack WITHOUT --dev switch

---

.env.dist
composer.json
composer.lock
config/bundles.php
config/packages/dev/swiftmailer.yaml
config/packages/swiftmailer.yaml
config/packages/test/swiftmailer.yaml
phpunit.xml.dist
symfony.lock

Add mailer from flex recipe, configuration, composer.lock, composer.json
Closes #27

Add mailer

---

composer.json
composer.lock
symfony.lock

Add symfony/templating

---

.env.dist

Copied .env.dist from team1 project

#43 - added database url in .env.dist

---

src/Resources/FOSUserBundle/views/Registration/register.html.twig
src/Resources/FOSUserBundle/views/layout.html.twig

Add overrides for Registration and FOSUser layout, stubs for custom js/css

---

src/Migrations/Version20180113194521.php

Added user migration
run
`php bin\console doctrine:migrations:migrate`
Closes #50

#50 - added user migration

---

composer.json
composer.lock
config/bundles.php
symfony.lock

Added doctrine-fixtures-bundle to project
run `composer install` 
Closes #53

#53 - added FixturesBundle

---

.gitignore
composer.json
composer.lock
config/bundles.php
symfony.lock

Add web-server-bundle

---

src/DataFixtures/UserFixtures.php

as described in title
run 
`php bin/console doctrine:fixtures:load`
Closes #52 .

#52 - added user fixtures for admin and visitor

---

circle.yml

Updated circle.yml, CircleCI switched to use migrations and not schema update.
Closes #51 .

#51 - updated circle.yml

---

.env.dist
README.md

- .env.dist updated with dev (vagrant) credentials
- README.md updated with setup instructions
Closes #67, #64.

Issue 64 readme

---

src/Entity/Item.php

Item entity class added.
Closes #69

#69 - added Item entity

---

src/Repository/ItemRepository.php

Repository for Item entity added.
Closes #70 .

#70 - added repository for Item entity

---

src/DataFixtures/ItemFixtures.php

Add fixtures for  3 Items and 3 Categories

---

src/DataFixtures/ItemFixtures.php
src/Entity/Item.php
src/Migrations/Version20180118123459.php

Add status field to Item
Add fixture for status field addition
Update Item fixture to set status
Closes #78 .

Issue 78 missing lost found flag

---

src/DataFixtures/PointFixtures.php
src/Entity/Point.php
src/Migrations/Version20180118125653.php
src/Repository/PointRepository.php

Add Point entity representing GPS locations
Add 4 random points in Zagreb as fixtures

Issue 83 point entity

---

.env.dist
circle.yml
config/services.yaml
public/css/style.css
public/js/app.js
public/js/gmaps.js
src/Controller/HomepageController.php
src/Entity/Location.php
src/Entity/Point.php
templates/base.html.twig
templates/homepage/index.html.twig

A basic integration of Google maps using a pure JS api called GMaps (https://github.com/hpneo/gmaps)
Renders points defined in fixtures as pins.
To install, copy:
```
###> google maps integration ###
GMAPS_API_KEY=AIzaSyD0Bt1BuVHedGQ8I_vK1L9PpCaD1fB7O-c
###< google maps integration ###
```
from .env.dist to .env
Todo for later: make overlays instead of pins for point sets.
Closes #63 
Closes #21  - we need to make a new issue for what to do next.

Issue 63 integrate google maps

---

src/Repository/CategoryRepository.php

Added CategoryRepository
Closed #73

#73 - added repository for Category entity

---

README.md

Migration instructions fixed.
Closes #91

#91 - migrations part of README.md fixed

---

src/Entity/Category.php
src/Entity/Item.php

As described in title.
Closes #93

#93 - removed setId(), added type hint for Category

---

src/DataFixtures/CategoryFixtures.php
src/DataFixtures/ItemFixtures.php
src/DataFixtures/PointAndLocationFixtures.php
src/Entity/Category.php
src/Entity/Item.php
src/Entity/Location.php
src/Migrations/Version20180119154853.php
src/Migrations/Version20180120110617.php

Closes #95 .
- Added relation betwen Item and Location (OneToMany Item->Location)
- Added migration to support that 
- Changed and refactored fixtures
**Only for dev environemnt**
To test or apply changes  after merging run:
- `php bin/console doctrine:database:drop --force`
- `php bin/console doctrine:database:create`
- `php bin/console doctrine:migrations:migrate`
- `php bin/console doctrine:fixtures:load`
**This PR have commit(s) from PR #94 to avoid merge conflict**

Issue 95 resolved

---

composer.json
composer.lock
config/bundles.php
config/services.yaml
symfony.lock

Added Vich\UploaderBundle\VichUploaderBundle for file uploading.
run
`composer install`
Closes #99

Issue 99 upload bundle
